"use client";

import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Sparkles, Users, ShieldIcon } from "lucide-react";
import CornerElements from "@/components/CornerElements";

const AboutPage = () => {
  return (
    <section className="relative z-10 pt-24 pb-32 flex-grow container mx-auto px-4">
      {/* Hero Section */}
      <div className="relative text-center mb-16">
        <CornerElements />
        <h1 className="text-4xl md:text-5xl font-bold mb-4 font-mono">
          About <span className="text-primary">CodeFlex.ai</span>
        </h1>
        <p className="text-muted-foreground max-w-2xl mx-auto text-lg">
          CodeFlex.ai is your AI-powered personal fitness assistant. Our mission is to provide personalized workout and diet plans to help you reach your goals faster.
        </p>
        <Button asChild size="lg" className="mt-8 bg-primary text-primary-foreground hover:bg-primary/90">
          <Link href="/generate-program">
            Get Your Personalized Plan
          </Link>
        </Button>
      </div>

      {/* Features Section */}
      <div className="grid md:grid-cols-3 gap-8 mb-16">
        <Card className="bg-card/90 backdrop-blur-sm border border-border p-6 text-center">
          <div className="mb-4 flex justify-center">
            <Sparkles className="h-8 w-8 text-primary" />
          </div>
          <h3 className="text-xl font-bold text-foreground mb-2">AI-Powered Workouts</h3>
          <p className="text-muted-foreground text-sm">
            Personalized workout plans generated by AI to match your fitness level and goals.
          </p>
        </Card>

        <Card className="bg-card/90 backdrop-blur-sm border border-border p-6 text-center">
          <div className="mb-4 flex justify-center">
            <Users className="h-8 w-8 text-primary" />
          </div>
          <h3 className="text-xl font-bold text-foreground mb-2">Community Support</h3>
          <p className="text-muted-foreground text-sm">
            Join a growing community of fitness enthusiasts and stay motivated on your journey.
          </p>
        </Card>

        <Card className="bg-card/90 backdrop-blur-sm border border-border p-6 text-center">
          <div className="mb-4 flex justify-center">
            <ShieldIcon className="h-8 w-8 text-primary" />
          </div>
          <h3 className="text-xl font-bold text-foreground mb-2">Safe & Trusted</h3>
          <p className="text-muted-foreground text-sm">
            AI-generated plans are designed with safety protocols in mind to avoid injuries.
          </p>
        </Card>
      </div>

      {/* Team Section (Optional Placeholder) */}
      <div className="text-center">
        <h2 className="text-3xl font-bold mb-6 font-mono">
          Meet the <span className="text-primary">Team</span>
        </h2>
        <p className="text-muted-foreground mb-8 max-w-xl mx-auto">
          Our passionate team combines AI technology with fitness expertise to bring you the best personalized experience.
        </p>
        <div className="grid md:grid-cols-3 gap-8">
          <Card className="bg-card/90 backdrop-blur-sm border border-border p-6 text-center">
            <div className="w-24 h-24 rounded-full bg-primary/10 mx-auto mb-4 flex items-center justify-center">
              <span className="text-2xl font-bold text-primary">A</span>
            </div>
            <h3 className="font-bold text-foreground mb-1">Alice</h3>
            <p className="text-muted-foreground text-sm">Founder & AI Specialist</p>
          </Card>

          <Card className="bg-card/90 backdrop-blur-sm border border-border p-6 text-center">
            <div className="w-24 h-24 rounded-full bg-primary/10 mx-auto mb-4 flex items-center justify-center">
              <span className="text-2xl font-bold text-primary">B</span>
            </div>
            <h3 className="font-bold text-foreground mb-1">Bob</h3>
            <p className="text-muted-foreground text-sm">Head of Fitness Programs</p>
          </Card>

          <Card className="bg-card/90 backdrop-blur-sm border border-border p-6 text-center">
            <div className="w-24 h-24 rounded-full bg-primary/10 mx-auto mb-4 flex items-center justify-center">
              <span className="text-2xl font-bold text-primary">C</span>
            </div>
            <h3 className="font-bold text-foreground mb-1">Charlie</h3>
            <p className="text-muted-foreground text-sm">AI & UX Designer</p>
          </Card>
        </div>
      </div>
    </section>
  );
};

export default AboutPage;
